// File generated by flutterfire_cli.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (identical(defaultTargetPlatform, TargetPlatform.android)) {
      return android;
    }
    if (identical(defaultTargetPlatform, TargetPlatform.iOS)) {
      return ios;
    }
    if (identical(defaultTargetPlatform, TargetPlatform.macOS)) {
      return macos;
    }
    if (identical(defaultTargetPlatform, TargetPlatform.windows)) {
      return windows;
    }
    if (identical(defaultTargetPlatform, TargetPlatform.linux)) {
      return linux;
    }
    throw UnsupportedError(
      'DefaultFirebaseOptions is not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGHejP0LBYqhea1P1RbKVkePlp_te143g',
    appId: '1:323623480798:android:3c5e8f7a9d6b2c1e0f',
    messagingSenderId: '323623480798',
    projectId: 'dbmsproject-651dd',
    storageBucket: 'dbmsproject-651dd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGHejP0LBYqhea1P1RbKVkePlp_te143g',
    appId: '1:323623480798:ios:5d4e3f2a1b0c9d8e7f',
    messagingSenderId: '323623480798',
    projectId: 'dbmsproject-651dd',
    storageBucket: 'dbmsproject-651dd.firebasestorage.app',
    iosBundleId: 'com.example.dbmsProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGHejP0LBYqhea1P1RbKVkePlp_te143g',
    appId: '1:323623480798:macos:5d4e3f2a1b0c9d8e7f',
    messagingSenderId: '323623480798',
    projectId: 'dbmsproject-651dd',
    storageBucket: 'dbmsproject-651dd.firebasestorage.app',
    iosBundleId: 'com.example.dbmsProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGHejP0LBYqhea1P1RbKVkePlp_te143g',
    appId: '1:323623480798:windows:7e8f9a0b1c2d3e4f5',
    messagingSenderId: '323623480798',
    projectId: 'dbmsproject-651dd',
    storageBucket: 'dbmsproject-651dd.firebasestorage.app',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyAGHejP0LBYqhea1P1RbKVkePlp_te143g',
    appId: '1:323623480798:linux:6d7e8f9a0b1c2d3e4',
    messagingSenderId: '323623480798',
    projectId: 'dbmsproject-651dd',
    storageBucket: 'dbmsproject-651dd.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGHejP0LBYqhea1P1RbKVkePlp_te143g',
    appId: '1:323623480798:web:9c8d7e6f5a4b3c2d1',
    messagingSenderId: '323623480798',
    projectId: 'dbmsproject-651dd',
    authDomain: 'dbmsproject-651dd.firebaseapp.com',
    storageBucket: 'dbmsproject-651dd.firebasestorage.app',
  );
}

